# Generated by Django 5.2.4 on 2025-09-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
